# Generated by Django 6.0.6 on 2026-07-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('age', models.CharField(max_length=50, verbose_name='Idade')),
                ('weight', models.CharField(max_length=50, verbose_name='Peso')),
                ('color', models.CharField(max_length=50, verbose_name='Cor')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível para adoção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem do Pet',
                'verbose_name_plural': 'Imagens do Pet',
            },
        ),
    ]
