# Generated by Django 6.0.6 on 2026-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petimage',
            options={'ordering': ['-is_cover', 'id'], 'verbose_name': 'Imagem do Pet', 'verbose_name_plural': 'Imagens do Pet'},
        ),
        migrations.AddField(
            model_name='petimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Capa (miniatura)'),
        ),
    ]
