# Generated by Django 6.0.6 on 2026-07-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_original_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='medio', max_length=20, verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species_other',
            field=models.CharField(blank=True, help_text='Preenchido quando a categoria é "Outro" (ex: Coelho, Ave).', max_length=50, verbose_name='Categoria (outro)'),
        ),
    ]
