# Generated by Django 6.0.6 on 2026-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_backfill_species_cachorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], default='macho', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species_other',
            field=models.CharField(blank=True, help_text='Preenchido quando a categoria é "Outro" (ex: Coelho, Ave).', max_length=50, verbose_name='Espécie (outro)'),
        ),
    ]
