# Generated by Django 6.0.6 on 2026-07-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_backfill_nala_sex_femea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='species_other',
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro')], default='cachorro', max_length=20, verbose_name='Espécie'),
        ),
    ]
